# See:
#   FLIT: https://flit.pypa.io/en/latest/pyproject_toml.html
#   TOML format: https://toml.io/en/

#
# Updating PyPi:
#   source venv/bin/activate
#   flit build
#   flit publish --repository sparclclient


[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"


[project]
name = "sparclclient"
authors = [
  { name="S. Pothier", email="datalab-spectro@noirlab.edu" },
]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
# version is found in: ~/sandbox/sparclclient/sparcl/__init__.py
dynamic = ["version", "description"]
dependencies = ["requests==2.31.0", "numpy>=1.23.5,<1.26.4", "spectres", "pyjwt"]

[project.urls]
"Homepage" = "https://github.com/pypa/sparclclient"
"Bug Tracker" = "https://github.com/pypa/sparclclient/issues"
"Documentation" = "https://sparclclient.readthedocs.io/en/latest/"

[tool.flit.module]
name = "sparcl"

[tool.flit.sdist]
exclude = ["**/UNPUBLISHED/", "**/OBSOLETE/"]

[tool.black]
# https://black.readthedocs.io/en/stable/usage_and_configuration/index.html
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''
